package jp.co.basenet.weolab.tms_service.exam.controller;

import jp.co.basenet.weolab.tms_service.exam.dto.Question;
import jp.co.basenet.weolab.tms_service.exam.dto.QuestionListResponse;
import jp.co.basenet.weolab.tms_service.exam.service.QuestionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * 問題コントローラ（REST API）
 */
@RestController
@RequestMapping("/api/questions")
public class QuestionController {

    @Autowired
    private QuestionService questionService;

    /**
     * 問題一覧を取得
     */
    @GetMapping
    public ResponseEntity<QuestionListResponse> getQuestions(
            @RequestParam(required = false) String questionId,
            @RequestParam(required = false) String skill,
            @RequestParam(required = false) Integer difficultyFrom,
            @RequestParam(required = false) Integer difficultyTo,
            @RequestParam(required = false) Boolean isAutoGenerated,
            @RequestParam(required = false) String keyword,
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "10") int size
    ) {
        Page<Question> pageResult = questionService.getQuestions(
                questionId, skill, difficultyFrom, difficultyTo, isAutoGenerated, keyword, page, size
        );
        QuestionListResponse response = new QuestionListResponse();
        response.setItems(pageResult.getContent());
        response.setTotal(pageResult.getTotalElements());

        return ResponseEntity.ok(response);

    }

    /**
     * 問題詳細を取得
     */
    @GetMapping("/{questionId}")
    public ResponseEntity<Question> getQuestion(@PathVariable String questionId) {
        Question question = questionService.getQuestion(questionId);
        return ResponseEntity.ok(question);
    }

    /**
     * 問題を保存（新規作成・更新）
     */
    @PostMapping
    public ResponseEntity<Question> saveQuestion(@RequestBody Question question) {
        Question saved = questionService.saveQuestion(question);
        return ResponseEntity.ok(saved);
    }

    /**
     * 問題を削除（論理削除）
     */
    @DeleteMapping("/{questionId}")
    public ResponseEntity<Void> deleteQuestion(@PathVariable String questionId) {
        questionService.deleteQuestion(questionId);
        return ResponseEntity.noContent().build();
    }
}