// ファイルパス: jp.co.basenet.weolab.tms_service.exam.entity.QuestionDoc.java

package jp.co.basenet.weolab.tms_service.exam.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * 問題ドキュメント（MongoDB 用）
 * 選択肢は内嵌（embedded）で保持
 */
@Document(collection = "question")
@Getter
@Setter
public class QuestionDoc {

    /**
     * 問題ID（主キー）
     */
    @Id
    @Indexed // 検索・削除用にインデックス
    private String questionId;

    /**
     * 問題文
     */
    private String questionText;

    /**
     * 難易度（1～5）
     */
    private Integer difficulty;

    /**
     * スキル名
     */
    private String skill;

    /**
     * 正解選択肢ID
     */
    private String modelAnswerChoiceId;

    /**
     * 正解理由
     */
    private String modelAnswerReason;

    /**
     * 自動生成フラグ
     */
    private Boolean isAutoGenerated = false;

    /**
     * 選択肢リスト（内嵌）
     */
    private List<ChoiceDoc> choices = new ArrayList<>();

    /**
     * 論理削除日時（null = 未削除）
     */
    private LocalDateTime deletedAt;

    /**
     * 作成日時
     */
    private LocalDateTime createdAt;

    /**
     * 更新日時
     */
    private LocalDateTime updatedAt;

    /**
     * 論理削除済みか判定
     */
    public boolean isDeleted() {
        return this.deletedAt != null;
    }

    /**
     * 選択肢ドキュメント（内嵌クラス）
     */
    @Getter
    @Setter
    public static class ChoiceDoc {
        private String choiceId;
        private String choiceText;
        private String reason;
        private LocalDateTime createdAt;
    }
}