package jp.co.basenet.weolab.tms_service.exam.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Where;

import java.time.LocalDateTime;

/**
 * 問題エンティティ（questionテーブル対応）
 */
@Entity
@Table(name = "question")
@Where(clause = "deleted_at IS NULL") // 論理削除済みレコードを自動除外
@Getter
@Setter
public class QuestionEntity {

    @Id
    @Column(name = "question_id", length = 36, nullable = false)
    private String questionId;

    @Column(name = "question_text", nullable = false, columnDefinition = "TEXT")
    private String questionText;

    @Column(name = "difficulty", nullable = false)
    private Integer difficulty;

    @Column(name = "skill", nullable = false, length = 50)
    private String skill;

    @Column(name = "model_answer_choice_id", length = 36)
    private String modelAnswerChoiceId;

    @Column(name = "model_answer_reason", columnDefinition = "TEXT")
    private String modelAnswerReason;

    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // 論理削除フラグ（アプリ層で使用）
    public boolean isDeleted() {
        return this.deletedAt != null;
    }
}