// ファイル: jp.co.basenet.weolab.tms_service.exam.repository.QuestionRepositoryImpl.java

package jp.co.basenet.weolab.tms_service.exam.repository;

import jp.co.basenet.weolab.tms_service.exam.entity.QuestionDoc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class QuestionRepositoryImpl implements QuestionRepositoryCustom {

    @Autowired
    private MongoTemplate mongoTemplate;

    @Override
    public Page<QuestionDoc> findWithFilters(
            String questionId,
            String skill,
            Integer difficultyFrom,
            Integer difficultyTo,
            Boolean isAutoGenerated,
            String keyword,
            Pageable pageable) {

        // 基本条件: 論理削除されていない
        Criteria criteria = Criteria.where("deletedAt").is(null);

        // 動的条件を追加
        if (questionId != null) {
            criteria.and("questionId").is(questionId);
        }
        if (skill != null) {
            criteria.and("skill").is(skill);
        }
        if (difficultyFrom != null) {
            criteria.and("difficulty").gte(difficultyFrom);
        }
        if (difficultyTo != null) {
            criteria.and("difficulty").lte(difficultyTo);
        }
        if (isAutoGenerated != null) {
            criteria.and("isAutoGenerated").is(isAutoGenerated);
        }
        if (keyword != null && !keyword.isEmpty()) {
            criteria.and("questionText").regex(keyword, "i");
        }

        Query query = Query.query(criteria).with(pageable);

        // 結果取得
        List<QuestionDoc> results = mongoTemplate.find(query, QuestionDoc.class);
        long total = mongoTemplate.count(Query.query(criteria), QuestionDoc.class);

        return new PageImpl<>(results, pageable, total);
    }
}