package jp.co.basenet.weolab.tms_service.exam.repository;

import jp.co.basenet.weolab.tms_service.exam.entity.ChoiceEntity;
import jp.co.basenet.weolab.tms_service.exam.entity.QuestionEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;


import java.util.List;

/**
 * 問題リポジトリ
 */
public interface QuestionRepository extends JpaRepository<QuestionEntity, String> {

    /**
     * 動的条件で問題を検索（ページネーション対応）
     */
    @Query("SELECT q FROM QuestionEntity q WHERE " +
            "(:questionId IS NULL OR q.questionId = :questionId) AND " +
            "(:skill IS NULL OR q.skill = :skill) AND " +
            "(:difficultyFrom IS NULL OR q.difficulty >= :difficultyFrom) AND " +
            "(:difficultyTo IS NULL OR q.difficulty <= :difficultyTo) AND " +
            "(:isAutoGenerated IS NULL OR q.isAutoGenerated = :isAutoGenerated) AND " +
            "(:keyword IS NULL OR q.questionText LIKE %:keyword%)")
    Page<QuestionEntity> findWithFilters(
            @Param("questionId") String questionId,
            @Param("skill") String skill,
            @Param("difficultyFrom") Integer difficultyFrom,
            @Param("difficultyTo") Integer difficultyTo,
            @Param("isAutoGenerated") Boolean isAutoGenerated,
            @Param("keyword") String keyword,
            Pageable pageable
    );

    /**
     * 指定問題IDの選択肢を取得（ChoiceRepositoryで代替可能だが、N+1問題回避のため）
     */
    @Query("SELECT c FROM ChoiceEntity c WHERE c.questionId = :questionId")
    List<ChoiceEntity> findChoicesByQuestionId(@Param("questionId") String questionId);
}