// ファイル: jp.co.basenet.weolab.tms_service.exam.repository.QuestionRepositoryCustom.java

package jp.co.basenet.weolab.tms_service.exam.repository;

import jp.co.basenet.weolab.tms_service.exam.entity.QuestionDoc;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface QuestionRepositoryCustom {
    Page<QuestionDoc> findWithFilters(
            String questionId,
            String skill,
            Integer difficultyFrom,
            Integer difficultyTo,
            Boolean isAutoGenerated,
            String keyword,
            Pageable pageable
    );
}