package jp.co.basenet.weolab.tms_service.exam.dto;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;

@Value
@Builder
@Jacksonized
public class Question {

  @JsonProperty("問題ＩＤ")
  String questionId;

  @JsonProperty("問題文章")
  String questionText;

  @JsonProperty("難易度")
  Integer difficulty;

  @JsonProperty("スキル")
  String skill;

  /** 正解の選択肢ID */
  @JsonProperty("模範回答")
  String modelAnswerId;

  @JsonProperty("模範回答理由")
  String modelAnswerReason;

  /** 0/1 で来る前提。booleanも可だが今回は元JSONに合わせて保持 */
  @JsonProperty("自動生成フラグ")
  int autoGeneratedFlag;

  @JsonProperty("選択肢")
  List<Choice> choices;

  // 便利メソッド：0/1 を boolean に
  @JsonIgnore
  public boolean isAutoGenerated() {
    return autoGeneratedFlag != 0;
  }

  // 便利メソッド：正解の選択肢を取得
  @JsonIgnore
  public Optional<Choice> getCorrectChoice() {
    if (modelAnswerId == null || choices == null) return Optional.empty();
    return choices.stream().filter(c -> modelAnswerId.equals(c.getChoiceId())).findFirst();
  }
}
