package jp.co.basenet.weolab.tms_service.exam.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.List;

/**
 * 問題DTO（フロントエンドとのやり取り用）
 * JSON出力時は日本語フィールド名を使用
 */
@Data
public class Question {

  @JsonProperty("問題ＩＤ")
  private String questionId;

  @JsonProperty("問題文章")
  private String questionText;

  @JsonProperty("難易度")
  private Integer difficulty;

  @JsonProperty("スキル")
  private String skill;

  @JsonProperty("模範回答")
  private String modelAnswerChoiceId;

  @JsonProperty("模範回答理由")
  private String modelAnswerReason;

  @JsonProperty("自動生成フラグ")
  private Boolean isAutoGenerated;

  @JsonProperty("選択肢")
  private List<Choice> choices;
}