// ファイルパス: jp.co.basenet.weolab.tms_service.exam.service.ExamPaperService.java

package jp.co.basenet.weolab.tms_service.exam.service;

import jp.co.basenet.weolab.tms_service.exam.dto.*;
import jp.co.basenet.weolab.tms_service.exam.entity.ExamPaperDoc;
import jp.co.basenet.weolab.tms_service.exam.entity.QuestionDoc;
import jp.co.basenet.weolab.tms_service.exam.repository.ExamPaperRepository;
import jp.co.basenet.weolab.tms_service.exam.repository.ExamAnswerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 試験用紙サービス（MongoDB 版）
 * 試験用紙と問題の関連は、QuestionDoc の ID を参照することで実現
 */
@Service
@Transactional
public class ExamPaperService {

    @Autowired
    private ExamPaperRepository examPaperRepository;

    @Autowired
    private QuestionService questionService;

    @Autowired
    private ExamAnswerRepository examAnswerRepository;

    /**
     * 試験実行用の試験用紙詳細を取得
     */
    @Transactional(readOnly = true)
    public ExamPaperDetailResponse getExamPaperForRun(String paperId) {
        var detail = getPaper(paperId);
        if (detail == null) return null;

        ExamPaperDetailResponse response = new ExamPaperDetailResponse();
        response.set試験用紙ＩＤ(detail.getPaper().getPaperId());
        response.set試験用紙名称(detail.getPaper().getPaperName());
        response.set説明(detail.getPaper().getDescription());
        response.set作成日時(detail.getPaper().getCreatedAt());
        response.setDeletedAt(detail.getPaper().getDeletedAt());

        // 問題リストを変換
        List<ExamPaperQuestion> questionList = detail.getQuestions().stream()
                .map(q -> {
                    ExamPaperQuestion epq = new ExamPaperQuestion();
                    epq.set試験用紙問題ＩＤ(q.getPaperQuestionId());
                    epq.set試験用紙ＩＤ(detail.getPaper().getPaperId());
                    epq.set問題文章(q.getQuestion().getQuestionText());
                    epq.set難易度(q.getQuestion().getDifficulty());
                    epq.setスキル(q.getQuestion().getSkill());
                    epq.set模範回答(q.getQuestion().getModelAnswerChoiceId());
                    epq.set模範回答理由(q.getQuestion().getModelAnswerReason());
                    epq.set自動生成フラグ(q.getQuestion().getIsAutoGenerated() ? 1 : 0);

                    List<Choice> choices = q.getChoices().stream()
                            .map(c -> {
                                Choice choice = new Choice();
                                choice.setChoiceId(c.getChoiceId());
                                choice.setChoiceText(c.getChoiceText());
                                choice.setReason(c.getReason());
                                return choice;
                            })
                            .collect(Collectors.toList());
                    epq.set選択肢(choices);
                    return epq;
                })
                .collect(Collectors.toList());

        response.set問題リスト(questionList);
        return response;
    }

    /**
     * 試験用紙詳細を取得（DTO用）
     */
    public ExamPaperDetail getPaper(String paperId) {
        var docOpt = examPaperRepository.findByPaperIdAndDeletedAtIsNull(paperId);
        if (docOpt.isEmpty()) {
            return null;
        }
        var doc = docOpt.get();

        var paperDto = new ExamPaperDetail.ExamPaper();
        paperDto.setPaperId(doc.getPaperId());
        paperDto.setPaperName(doc.getPaperName());
        paperDto.setDescription(doc.getDescription());
        paperDto.setCreatedAt(doc.getCreatedAt());
        paperDto.setDeletedAt(doc.getDeletedAt());

        // 問題参照をソートして詳細を取得
        var questionDtos = doc.getQuestions().stream()
                .sorted(Comparator.comparing(ExamPaperDoc.QuestionRef::getDisplayOrder))
                .map(pq -> {
                    // QuestionDoc を取得（MongoDB）
                    Question questionDto = questionService.getQuestion(pq.getQuestionId());
                    if (questionDto == null) {
                        throw new RuntimeException("関連する問題が見つかりません: " + pq.getQuestionId());
                    }

                    var qDto = new ExamPaperDetail.ExamPaperQuestionWithContent();
                    qDto.setPaperQuestionId(pq.getPaperQuestionId());
                    qDto.setQuestion(questionDto);
                    qDto.setChoices(questionDto.getChoices());
                    return qDto;
                })
                .collect(Collectors.toList());

        var detail = new ExamPaperDetail();
        detail.setPaper(paperDto);
        detail.setQuestions(questionDtos);
        return detail;
    }

    /**
     * 試験用紙を保存（新規作成または更新）
     */
    public String savePaper(ExamPaperRequest request) {
        String paperId = request.getPaperId();
        boolean isNew = (paperId == null || paperId.isEmpty() ||
                examPaperRepository.findByPaperIdAndDeletedAtIsNull(paperId).isEmpty());

        ExamPaperDoc paper;
        if (isNew) {
            paper = createPaper(request);
        } else {
            paper = updatePaper(request);
        }
        return paper.getPaperId();
    }

    /**
     * 新規試験用紙を作成
     */
    private ExamPaperDoc createPaper(ExamPaperRequest request) {
        String paperId = request.getPaperId();
        if (paperId == null || paperId.isEmpty()) {
            paperId = UUID.randomUUID().toString();
        }

        ExamPaperDoc paper = new ExamPaperDoc();
        paper.setPaperId(paperId);
        paper.setPaperName(request.getPaper().getPaperName());
        paper.setDescription(request.getPaper().getDescription());
        LocalDateTime now = LocalDateTime.now();
        paper.setCreatedAt(now);
        paper.setUpdatedAt(now);

        // 新規問題を保存
        List<String> newQuestionIds = new ArrayList<>();
        if (request.getNewQuestions() != null) {
            for (var q : request.getNewQuestions()) {
                var savedQuestion = questionService.saveQuestion(q);
                newQuestionIds.add(savedQuestion.getQuestionId());
            }
        }

        // 問題参照を構築
        List<ExamPaperDoc.QuestionRef> refs = new ArrayList<>();
        int order = 1;

        // 既存問題の参照
        if (request.getQuestionRefs() != null) {
            for (var ref : request.getQuestionRefs()) {
                String qId = ref.getQuestionId();
                Question qDto = questionService.getQuestion(qId);
                if (qDto == null) {
                    throw new RuntimeException("問題が見つかりません: " + qId);
                }

                ExamPaperDoc.QuestionRef pq = new ExamPaperDoc.QuestionRef();
                pq.setPaperQuestionId(
                        ref.getPaperQuestionId() != null ? ref.getPaperQuestionId() : UUID.randomUUID().toString()
                );
                pq.setQuestionId(qId);
                pq.setDisplayOrder(order++);
                pq.setSkill(qDto.getSkill());
                pq.setDifficulty(qDto.getDifficulty());
                pq.setModelAnswerChoiceId(qDto.getModelAnswerChoiceId());
                refs.add(pq);
            }
        }

        // 新規作成問題の参照
        for (String qId : newQuestionIds) {
            Question qDto = questionService.getQuestion(qId);
            ExamPaperDoc.QuestionRef pq = new ExamPaperDoc.QuestionRef();
            pq.setPaperQuestionId(UUID.randomUUID().toString());
            pq.setQuestionId(qId);
            pq.setDisplayOrder(order++);
            pq.setSkill(qDto.getSkill());
            pq.setDifficulty(qDto.getDifficulty());
            pq.setModelAnswerChoiceId(qDto.getModelAnswerChoiceId());
            refs.add(pq);
        }

        paper.setQuestions(refs);
        examPaperRepository.save(paper);
        return paper;
    }

    /**
     * 既存試験用紙を更新
     */
    private ExamPaperDoc updatePaper(ExamPaperRequest request) {
        String paperId = request.getPaperId();

        // 試験用紙が使用済みか確認
        var existingOpt = examPaperRepository.findByPaperIdAndDeletedAtIsNull(paperId);
        if (existingOpt.isEmpty()) {
            throw new RuntimeException("試験用紙が見つかりません: " + paperId);
        }
        var existing = existingOpt.get();

        // 使用済みかチェック（回答があるか）
        List<String> paperQuestionIds = existing.getQuestions().stream()
                .map(ExamPaperDoc.QuestionRef::getPaperQuestionId)
                .toList();

        boolean isUsed = examAnswerRepository.existsByPaperQuestionIdIn(paperQuestionIds);
        if (isUsed) {
            throw new RuntimeException("この試験用紙は既に使用されているため、編集できません。");
        }

        // 試験用紙基本情報を更新
        existing.setPaperName(request.getPaper().getPaperName());
        existing.setDescription(request.getPaper().getDescription());
        existing.setUpdatedAt(LocalDateTime.now());

        // 新規問題を保存
        List<String> newQuestionIds = new ArrayList<>();
        if (request.getNewQuestions() != null) {
            for (var q : request.getNewQuestions()) {
                var savedQuestion = questionService.saveQuestion(q);
                newQuestionIds.add(savedQuestion.getQuestionId());
            }
        }

        // 新しい問題参照を構築
        List<ExamPaperDoc.QuestionRef> refs = new ArrayList<>();
        int order = 1;

        if (request.getQuestionRefs() != null) {
            for (var ref : request.getQuestionRefs()) {
                String qId = ref.getQuestionId();
                Question qDto = questionService.getQuestion(qId);
                if (qDto == null) {
                    throw new RuntimeException("問題が見つかりません: " + qId);
                }

                ExamPaperDoc.QuestionRef pq = new ExamPaperDoc.QuestionRef();
                pq.setPaperQuestionId(
                        ref.getPaperQuestionId() != null ? ref.getPaperQuestionId() : UUID.randomUUID().toString()
                );
                pq.setQuestionId(qId);
                pq.setDisplayOrder(order++);
                pq.setSkill(qDto.getSkill());
                pq.setDifficulty(qDto.getDifficulty());
                pq.setModelAnswerChoiceId(qDto.getModelAnswerChoiceId());
                refs.add(pq);
            }
        }

        for (String qId : newQuestionIds) {
            Question qDto = questionService.getQuestion(qId);
            ExamPaperDoc.QuestionRef pq = new ExamPaperDoc.QuestionRef();
            pq.setPaperQuestionId(UUID.randomUUID().toString());
            pq.setQuestionId(qId);
            pq.setDisplayOrder(order++);
            pq.setSkill(qDto.getSkill());
            pq.setDifficulty(qDto.getDifficulty());
            pq.setModelAnswerChoiceId(qDto.getModelAnswerChoiceId());
            refs.add(pq);
        }

        existing.setQuestions(refs);
        examPaperRepository.save(existing);
        return existing;
    }

    /**
     * 試験用紙を論理削除
     */
    public void deletePaper(String paperId) {
        var docOpt = examPaperRepository.findByPaperIdAndDeletedAtIsNull(paperId);
        if (docOpt.isEmpty()) {
            return;
        }
        var doc = docOpt.get();
        doc.setDeletedAt(LocalDateTime.now());
        examPaperRepository.save(doc);
    }

    /**
     * キーワード検索（試験用紙名または説明）
     */
    public Page<ExamPaperDoc> findByKeyword(String keyword, Pageable pageable) {
        return examPaperRepository.findByKeyword(keyword, pageable);
    }

    /**
     * フィルタ検索
     */
    public Page<ExamPaperDoc> findByFilters(String name, String description, Pageable pageable) {
        return examPaperRepository.findByFilters(name, description, pageable);
    }

    /**
     * 試験用紙基本情報を取得（問題リストなし）
     */
    @Transactional(readOnly = true)
    public ExamPaperDetailResponse getExamPaperById(String paperId) {
        return getExamPaperForRun(paperId);
    }
}