// ファイルパス: jp.co.basenet.weolab.tms_service.exam.service.QuestionService.java

package jp.co.basenet.weolab.tms_service.exam.service;

import jp.co.basenet.weolab.tms_service.exam.dto.Choice;
import jp.co.basenet.weolab.tms_service.exam.dto.Question;
import jp.co.basenet.weolab.tms_service.exam.entity.QuestionDoc;
import jp.co.basenet.weolab.tms_service.exam.repository.QuestionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 問題サービス（MongoDB 版）
 */
@Service
@Transactional
public class QuestionService {

    @Autowired
    private QuestionRepository questionRepository;

    /**
     * 問題一覧を取得（フィルタ・ページネーション対応、論理削除除外）
     */
    @Transactional(readOnly = true)
    public Page<Question> getQuestions(
            String questionId,
            String skill,
            Integer difficultyFrom,
            Integer difficultyTo,
            Boolean isAutoGenerated,
            String keyword,
            int page,
            int size
    ) {
        Pageable pageable = PageRequest.of(page - 1, size); // フロントは1始まり
        Page<QuestionDoc> docs = questionRepository.findWithFilters(
                questionId, skill, difficultyFrom, difficultyTo, isAutoGenerated, keyword, pageable
        );
        return docs.map(this::toDto);
    }

    /**
     * 問題詳細を取得（論理削除されていないもののみ）
     */
    @Transactional(readOnly = true)
    public Question getQuestion(String questionId) {
        QuestionDoc doc = questionRepository.findById(questionId)
                .filter(q -> q.getDeletedAt() == null) // 論理削除チェック
                .orElseThrow(() -> new RuntimeException("問題が見つかりません: " + questionId));
        return toDto(doc);
    }

    /**
     * 問題を保存（新規作成・更新の両方対応）
     */
    public Question saveQuestion(Question dto) {
        String questionId = dto.getQuestionId();
        if (questionId == null || questionId.isEmpty()) {
            questionId = UUID.randomUUID().toString();
        }

        QuestionDoc doc = new QuestionDoc();
        doc.setQuestionId(questionId);
        doc.setQuestionText(dto.getQuestionText());
        doc.setDifficulty(dto.getDifficulty());
        doc.setSkill(dto.getSkill());
        doc.setModelAnswerChoiceId(dto.getModelAnswerChoiceId());
        doc.setModelAnswerReason(dto.getModelAnswerReason());
        doc.setIsAutoGenerated(dto.getIsAutoGenerated() != null ? dto.getIsAutoGenerated() : false);

        LocalDateTime now = LocalDateTime.now();
        // 既存ドキュメントがあれば createdAt を維持
        questionRepository.findById(questionId)
                .ifPresentOrElse(
                        existing -> doc.setCreatedAt(existing.getCreatedAt()),
                        () -> doc.setCreatedAt(now)
                );
        doc.setUpdatedAt(now);

        // 選択肢を内嵌
        if (dto.getChoices() != null) {
            doc.setChoices(dto.getChoices().stream().map(choiceDto -> {
                QuestionDoc.ChoiceDoc choiceDoc = new QuestionDoc.ChoiceDoc();
                String choiceId = choiceDto.getChoiceId();
                if (choiceId == null || choiceId.isEmpty()) {
                    choiceId = UUID.randomUUID().toString();
                }
                choiceDoc.setChoiceId(choiceId);
                choiceDoc.setChoiceText(choiceDto.getChoiceText());
                choiceDoc.setReason(choiceDto.getReason());
                choiceDoc.setCreatedAt(now);
                return choiceDoc;
            }).collect(Collectors.toList()));
        }

        questionRepository.save(doc);
        return getQuestion(questionId); // 関連データを含めて再取得
    }

    /**
     * 問題を論理削除
     */
    public void deleteQuestion(String questionId) {
        QuestionDoc doc = questionRepository.findById(questionId)
                .orElseThrow(() -> new RuntimeException("問題が見つかりません: " + questionId));
        doc.setDeletedAt(LocalDateTime.now());
        questionRepository.save(doc);
    }

    // --- ヘルパーメソッド ---

    private Question toDto(QuestionDoc doc) {
        Question dto = new Question();
        dto.setQuestionId(doc.getQuestionId());
        dto.setQuestionText(doc.getQuestionText());
        dto.setDifficulty(doc.getDifficulty());
        dto.setSkill(doc.getSkill());
        dto.setModelAnswerChoiceId(doc.getModelAnswerChoiceId());
        dto.setModelAnswerReason(doc.getModelAnswerReason());
        dto.setIsAutoGenerated(doc.getIsAutoGenerated());

        if (doc.getChoices() != null) {
            dto.setChoices(doc.getChoices().stream().map(choiceDoc -> {
                Choice choiceDto = new Choice();
                choiceDto.setChoiceId(choiceDoc.getChoiceId());
                choiceDto.setChoiceText(choiceDoc.getChoiceText());
                choiceDto.setReason(choiceDoc.getReason());
                return choiceDto;
            }).collect(Collectors.toList()));
        }
        return dto;
    }
}